# Generated by Django 4.1.7 on 2023-02-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('XC', 'cross-country'), ('DH', 'downhill'), ('CX', 'cyclo-cross'), ('FR', 'freeride'), ('DJ', 'dirt-jump'), ('MX', 'marathon')], max_length=15)),
                ('is_uci_regulated', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_riders', models.IntegerField()),
                ('stages', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('event_weight', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UciPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_position', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=50)),
                ('stage_number', models.IntegerField()),
                ('track_length_meters', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_api.events')),
            ],
        ),
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('uci_points_total', models.DecimalField(decimal_places=2, max_digits=20000)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events_api.locations')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events_api.teams')),
            ],
        ),
        migrations.CreateModel(
            name='RaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_time', models.TimeField()),
                ('position', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_api.events')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_api.riders')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_api.tracks')),
            ],
        ),
        migrations.CreateModel(
            name='EventWeatherConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.TextField(max_length=50)),
                ('avg_temp', models.FloatField(max_length=200)),
                ('avg_wind_speed', models.FloatField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_api.events')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_api.locations'),
        ),
        migrations.CreateModel(
            name='EventGeospatialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_api.events')),
            ],
        ),
    ]
