# Generated by Django 4.1.7 on 2023-02-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riders',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_api.locations'),
        ),
        migrations.AlterField(
            model_name='riders',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_api.teams'),
        ),
    ]
